#The name of your workflow.
name:  Test, build and deploy
# Trigger the workflow on push or pull request

on:
    push:
     branches: [ "dev" ]
    
#A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:

  test:
    #The type of machine to run the job on. [windows,macos, ubuntu , self-hosted]
    runs-on: ubuntu-latest
    #sequence of tasks called
    steps:
      # The branch or tag ref that triggered the workflow will be checked out.
      # https://github.com/actions/checkout
      - uses: actions/checkout@v1
      # Setup a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.14'
          channel: 'dev'
      - run: flutter  config --enable-web
      -  run: flutter  config --enable-linux-desktop
      #- run: flutter pub get
      #- run: flutter analyze
      #- run: flutter test
      - run: flutter build apk --release
